version: '3'

volumes:
  app_local_postgres_data: {}
  app_local_postgres_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: app_local_django
    container_name: app_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
      - mailhog
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: app_production_postgres
    container_name: app_local_postgres
    volumes:
      - app_local_postgres_data:/var/lib/postgresql/data:Z
      - app_local_postgres_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: app_local_mailhog
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    container_name: app_local_redis
    ports:
      - "6379:6379"

  celeryworker:
    <<: *django
    image: app_local_celeryworker
    container_name: app_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: app_local_celerybeat
    container_name: app_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat
