version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_backups: {}
  production_django_mediafiles: {}
  production_django_staticfiles: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: production_django
    platform: linux/x86_64
    volumes:
      - production_django_mediafiles:/app/mediafiles
      - production_django_staticfiles:/app/staticfiles
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    restart: unless-stopped

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres
    restart: unless-stopped

  nginx:
    build:
      context: ./
      dockerfile: ./compose/production/nginx/Dockerfile
    image: production_nginx
    depends_on:
      - django
    volumes:
      - production_django_mediafiles:/app/mediafiles:ro
      - production_django_staticfiles:/app/staticfiles:ro
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:5555:5555"
    restart: unless-stopped

  redis:
    image: redis:6
    restart: unless-stopped

  celeryworker:
    <<: *django
    image: production_celeryworker
    command: /start-celeryworker
    restart: unless-stopped

  celerybeat:
    <<: *django
    image: production_celerybeat
    command: /start-celerybeat
    restart: unless-stopped
